### ISSUE TITLE
Licence not specified

### ISSUE THREAD

**Issue by monkeypants** [Jsyro/untp-models#6]
Do you plan to licence this code?

a pydantic expression of spec-untp seems like a handy thing for python users, especially with all the first generation untp stuff happening in the js/ts ecosystem. But without an open source licence that’s compatible with people’s projects, they might be reluctant to use it (or contribute back).

**Comment by Jsyro** [comment]
Good Suggestion. 

Added GNU Public Licence (to align with UNTP Spec licence).
